# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d210e615a52b167feb9ab78bb2637f3a70911cef949c39ffe12c7f34fdb36b7b04ced74b61751976850bc61f2802bca722714625981b5d538c2508f9516aba0b

test:
  secret_key_base: 9b3fe3c8e15f11f1e8dcaec3d8dfc4eda799b72d0b90599cd5a4ae1e121b8d9f187c8ef6fa09c75336be4b6d5fd5c612d598377dcfd293b89f72c38fdde92afa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
